apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eve-system

resources:
  - namespace.yaml
  - secrets.yaml
  - rbac.yaml
  - deployment.yaml

commonLabels:
  app.kubernetes.io/part-of: eve

images:
  - name: harbor.home.lab/restack/eve
    newTag: latest
