apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eve-memory-sqlite
  labels:
    app: eve
    component: memory
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
